name: Docker Image CI

on:
  push:
    paths-ignore:
      - 'README.*'
      - 'img/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'README.*'
      - 'img/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag exasol-client:latest
    - name: Check the version
      run: docker run --rm exasol-client:latest --version
